### ISSUE TITLE
How to extract 3D mesh from a .package file

### ISSUE THREAD

**Issue by PAULYZHENG** [sims4toolkit/models#12]
Excellent project!

Does your library support the feature of **the extraction of 3D mesh from a .package file**? 

or just extrect the metadata of mesh geometry?

Many thanks!

**Comment by frankkulak** [comment]
For future reference, GitHub issues is not the place to ask these kinds of questions. It is meant for bug reports, questions about odd behavior, etc. You can ask these questions in my [Discord server](https://discord.gg/qNhD3Jh) instead.

But to answer your question, you can extract anything from any package with S4TK, assuming all you want is the raw data. All you need is the resource key (type, group, instance), and you can get the file's data as a buffer.

However, if you want to process the mesh at all, you'll have to look into other tools or 3rd party libraries - S4TK does not have a model for meshes or other file types related to CC (it is primarily intended for use with gameplay mods). You can also read [the docs](https://sims4toolkit.com/#/docs/models) to see what kinds of files are supported.

**Comment by PAULYZHENG** [comment]
Thank you Frank. Your answer helps a lot.
